- name: Install PostgreSQL
  ansible.builtin.package:
    name: "{{ 'postgresql' if ansible_os_family == 'Debian' else 'postgresql@14' }}"
    state: present
  become: "{{ ansible_os_family != 'Darwin' }}"

- name: Install PostgreSQL contrib
  ansible.builtin.package:
    name: postgresql-contrib
    state: present
  become: yes
  when: ansible_os_family == 'Debian'