- name: Copy requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: "{{ project_dir }}/requirements.txt"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid if ansible_os_family == 'Debian' else 'staff' }}"
    mode: '0644'
  become: yes

- name: Install Python dependencies
  ansible.builtin.pip:
    requirements: "{{ project_dir }}/requirements.txt"
    virtualenv: "{{ venv_dir }}"
  become: no